proc StochasticWarpBinding()
{
  string $obj;
  string $sel[] = `ls -sl`;
  if (size($sel) != 2) {
      print("You should select 2 objects\n");
      return;
  }
  else{
    for ($obj in $sel) {
        print($obj + "\n");
    }
    $cage = $sel[0];
    $target = $sel[1];
    print("Cage: " + $cage + "\n");
    print("Target: " + $target + "\n");

    // print number of vertices of cage
    int $numVertices = `polyEvaluate -v $cage`;
    // get the list of vertices
    
  }
}

